//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_CSharp_09_01_2023
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExam
    {
        public byte examId { get; set; }
        public string examName { get; set; }
        public Nullable<double> examMark { get; set; }
        public Nullable<System.DateTime> examDate { get; set; }
        public Nullable<byte> stuId { get; set; }
        public Nullable<byte> couId { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }

        public override string ToString()
        {
            return $"{{{nameof(examId)}={examId.ToString()}, {nameof(examName)}={examName}, {nameof(examMark)}={examMark.ToString()}, {nameof(examDate)}={examDate.ToString()}, {nameof(stuId)}={stuId.ToString()}, {nameof(couId)}={couId.ToString()}, {nameof(createAt)}={createAt.ToString()}, {nameof(updateAt)}={updateAt.ToString()}}}";
        }
    }
}
