global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using ExeciseOop.Entity;
global using ExeciseOop.Helpers;
global using System.Globalization;
global using ExeciseOop.Service;